name: HERBOLARIO PEPITA
favicon: null
layout_spectrum: 0.942045540548861
typography_spectrum: 0.962172529194504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9715684880502522
  lightness: 0.4485391245689243
  saturation: 0.30114206694997847
  rhythmicContrast: 0.5370133130345494
purpose: []
